GET  http://127.0.0.1:8000/api/books/
Content-Type: application/json

###
GET  http://127.0.0.1:8000/api/books/1/
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/auth/users/
Content-Type: application/json

{
    "username": "test",
    "email": "test@test.ru",
    "password": "user123456"
}

###
POST http://127.0.0.1:8000/api/auth/users/
Content-Type: application/json

{
    "username": "erass",
    "email": "test@test.ru",
    "password": "user123456"
}
###
POST http://127.0.0.1:8000/api/auth/jwt/create/
Content-Type: application/json

{
    "username": "erass",
    "password": "user123456"
}