### Получение всех книг
GET   http://127.0.0.1:8000/api/books/
Content-Type: application/json




### Получение книги по id
GET http://127.0.0.1:8000/api/books/1/
Content-Type: application/json

### Получение книги по id
POST  http://127.0.0.1:8000/api/books/3/
Content-Type: application/json



###
GET http://127.0.0.1:8000/api/authors/1/
Content-Type: application/json  


### Поиск книг
GET http://127.0.0.1:8000/api/books/search/?search=Жамила
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/books/search/?search=1200s



### Регистрация
POST   http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
    "username": "test",
    "email": "test@test.ru",
    "password": "123456"
    
}

### Логин
POST   http://127.0.0.1:8000/api/auth/login/ 
Content-Type: application/json

{
    "username": "test",
    "password": "123456"
    
}

### Тест токена
GET http://127.0.0.1:8000/api/auth/test_token/
Content-Type: application/json  
Authorization: Token 5e410554bf1bd1b0dbd6dc51b4eb6c859df3d9a8

###
### Получение списка избранных книг
GET http://127.0.0.1:8000/api/books/favorite/
Content-Type: application/json
Authorization: Token 5e410554bf1bd1b0dbd6dc51b4eb6c859df3d9a8



###
POST http://127.0.0.1:8000/api/cart/
Content-Type: application/json
Authorization: Token 5e410554bf1bd1b0dbd6dc51b4eb6c859df3d9a8

{
    "user": "3"
}

### Получение количества товаров в корзине
GET http://127.0.0.1:8000/api/cart/
Authorization: Token 5e410554bf1bd1b0dbd6dc51b4eb6c859df3d9a8


### Добавление товара в корзину
POST http://127.0.0.1:8000/api/cart-items/
Content-Type: application/json
Authorization: Token 5e410554bf1bd1b0dbd6dc51b4eb6c859df3d9a8

{
    "cart": 3,
    "book": 1
}


### 
POST http://127.0.0.1:8000/api/orders/
Content-Type: application/json
Authorization: Token 5e410554bf1bd1b0dbd6dc51b4eb6c859df3d9a8

{
    "user": 1,
    "cart": 3,
    "delivery_address": "Kyrgyzstan",
    "total_price": 1000,
    "payment_status": "Наличными"

}

### Получение списка заказов
GET http://127.0.0.1:8000/api/orders/
Authorization: Token 5e410554bf1bd1b0dbd6dc51b4eb6c859df3d9a8


###


