# Generated by Django 5.1.3 on 2024-11-19 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('paiment_status', models.CharField(default='new', max_length=100, verbose_name='Статус оплаты')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('done', 'Готов'), ('canceled', 'Отменен')], default='new', max_length=100, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('books', models.ManyToManyField(to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
