# Generated by Django 5.1.3 on 2024-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paiment_status',
            field=models.CharField(max_length=100, verbose_name='Статус оплаты'),
        ),
    ]
