# Generated by Django 5.1.3 on 2024-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comentbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentbook',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
