# Generated by Django 5.1.3 on 2024-11-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comentbook_created_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book'),
        ),
    ]
