# Generated by Django 5.1.3 on 2024-11-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_comentbook_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentbook',
            old_name='comment',
            new_name='coment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paiment_status',
            new_name='payment_status',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('year_birth', models.PositiveSmallIntegerField(verbose_name='Год рождения')),
                ('life_story', models.TextField(verbose_name='Краткая биография')),
                ('aut_image', models.ImageField(upload_to='', verbose_name='Фотография автора')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('aut_books', models.ManyToManyField(related_name='aut_books', to='books.book')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
    ]
