# Generated by Django 5.1.3 on 2024-11-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_comment_comentbook_coment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='books.book'),
        ),
    ]
