# Generated by Django 5.1.3 on 2024-11-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_discount_price_book_isbn_book_pages_book_stock_and_more'),
        ('books', '0008_alter_comentbook_book'),
    ]

    operations = [
    ]
