# Generated by Django 5.1.3 on 2024-12-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_order_book_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='bool',
            new_name='book',
        ),
    ]
